version: '2'
services:
  app:
    container_name: nodejs-mongodb-project
    restart: always
    build: .
    ports:
      - '80:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
